[33mcommit 2d4e928b7efb459cb281ac964927f432fb25c70e[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m)[m
Author: sotetu-79 <sotetu79@gmail.com>
Date:   Sat May 27 22:41:58 2023 +0900

    再修正

[1mdiff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml[m
[1mdeleted file mode 100644[m
[1mindex 8fa02f5..0000000[m
[1m--- a/.github/workflows/firebase-hosting-merge.yml[m
[1m+++ /dev/null[m
[36m@@ -1,20 +0,0 @@[m
[31m-# This file was auto-generated by the Firebase CLI[m
[31m-# https://github.com/firebase/firebase-tools[m
[31m-[m
[31m-name: Deploy to Firebase Hosting on merge[m
[31m-'on':[m
[31m-  push:[m
[31m-    branches:[m
[31m-      - main[m
[31m-jobs:[m
[31m-  build_and_deploy:[m
[31m-    runs-on: ubuntu-latest[m
[31m-    steps:[m
[31m-      - uses: actions/checkout@v3[m
[31m-      - run: npm ci && npm run build[m
[31m-      - uses: FirebaseExtended/action-hosting-deploy@v0[m
[31m-        with:[m
[31m-          repoToken: '${{ secrets.GITHUB_TOKEN }}'[m
[31m-          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUICK_URL_B0462 }}'[m
[31m-          channelId: live[m
[31m-          projectId: quick-url-b0462[m
[1mdiff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml[m
[1mdeleted file mode 100644[m
[1mindex ba7408a..0000000[m
[1m--- a/.github/workflows/firebase-hosting-pull-request.yml[m
[1m+++ /dev/null[m
[36m@@ -1,17 +0,0 @@[m
[31m-# This file was auto-generated by the Firebase CLI[m
[31m-# https://github.com/firebase/firebase-tools[m
[31m-[m
[31m-name: Deploy to Firebase Hosting on PR[m
[31m-'on': pull_request[m
[31m-jobs:[m
[31m-  build_and_preview:[m
[31m-    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'[m
[31m-    runs-on: ubuntu-latest[m
[31m-    steps:[m
[31m-      - uses: actions/checkout@v3[m
[31m-      - run: npm ci && npm run build[m
[31m-      - uses: FirebaseExtended/action-hosting-deploy@v0[m
[31m-        with:[m
[31m-          repoToken: '${{ secrets.GITHUB_TOKEN }}'[m
[31m-          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUICK_URL_B0462 }}'[m
[31m-          projectId: quick-url-b0462[m

[33mcommit 38258548eb2ee27dbb3087e5f4ba8c1f70a592d9[m
Author: sotetu-79 <sotetu79@gmail.com>
Date:   Sat May 27 21:32:08 2023 +0900

    import文の再修正

[1mdiff --git a/.firebase/hosting.YnVpbGQ.cache b/.firebase/hosting.YnVpbGQ.cache[m
[1mindex 14e02dd..f7c2dd6 100644[m
[1m--- a/.firebase/hosting.YnVpbGQ.cache[m
[1m+++ b/.firebase/hosting.YnVpbGQ.cache[m
[36m@@ -1,17 +1,14 @@[m
 favicon.ico,1684674487826,2da2a80121f173e07a9872fd3eac37a7cc021449ec0037d3c5cc624902cedc09[m
[31m-logo192.png,1684638166055,3ee59515172ee198f3be375979df15ac5345183e656720a381b8872b2a39dc8b[m
[31m-logo512.png,1684638166135,ee7e2f3fdb8209c4b6fd7bef6ba50d1b9dba30a25bb5c3126df057e1cb6f5331[m
 manifest.json,1684638165287,aff3449bdc238776f5d6d967f19ec491b36aed5fb7f23ccff6500736fd58494a[m
 robots.txt,1684638166842,bfe106a3fb878dc83461c86818bf74fc1bdc7f28538ba613cd3e775516ce8b49[m
[31m-index.html,1684916163941,838c57b929d10809431424384ff6b35b000d6faba9e0d271884e68e5c342ed89[m
[31m-asset-manifest.json,1684916163941,da23f0e5ae24cbd6bb34d440488af230a1becdfa6005230c8252d095f8ab7eb9[m
[31m-static/js/787.c49e00e7.chunk.js,1684916163958,61d1075a5af8d27045861f8bb986897f1af9592f542ca29908d4bd85967f0564[m
[31m-static/js/787.c49e00e7.chunk.js.map,1684916163958,ab729b8a1e439b209352404a99fd0253de5e06f4db22b5c10141cd7c85c68781[m
[31m-static/js/main.39b21671.js.LICENSE.txt,1684916163958,a966b5a07f0f1b04c22b1a4b17153cf651cb5386e5380302752c0fd378bf2f06[m
[31m-static/media/icon.35f11a99fb2a32658cd7.png,1684916163958,6d08c3862a35465d53b5ce8b5aa35cd93b4d4cfcc6e6b38d26103101cf20bcf5[m
[31m-static/media/notFound-1.75c77d00f28c055f73df.png,1684916163958,c06c5e093df1df508c711d9b53f9513f135ee0889d01251fa716ad6d3e795a40[m
[31m-static/media/background.e8488a7314a0d73c0542.png,1684916163958,0dde5d01fe7b74787bea728f611c12fb7b689f19a257875c02c3671ffebf65ac[m
[31m-static/media/question-1.9fb207f327cc85628ce9.png,1684916163958,7f3a94375dfa20661e6e9b1ce24d7305252c2ae1a42dc802f9683bce8cdddc1a[m
[31m-static/media/question-2.436db4cdd9b084e8bf7f.png,1684916163958,17ee542fe34a1e6d1e4d99f7128372220702ae50253cbca14131ba03c95ee6cb[m
[31m-static/js/main.39b21671.js,1684916163958,781b82c65aa2b7991762f529ed0dd105b3943c8ab36c3fbec6c4e97e9c61bfc5[m
[31m-static/js/main.39b21671.js.map,1684916163961,09d6a9d118b995c0a5b7d850114d72fc08c738e3913131716007270a43d3e3cf[m
[32m+[m[32masset-manifest.json,1685190608008,ddf98ad94b5b97fc555adcafd2b09c33aa8cd69c792bf25dc2ae0f8ff44b4635[m
[32m+[m[32mindex.html,1685190608008,c64f0a060d684bd4e317cb62adfee82d3d526f18d96b6e63c049fddb481396f9[m
[32m+[m[32mstatic/js/787.c49e00e7.chunk.js,1685190608023,61d1075a5af8d27045861f8bb986897f1af9592f542ca29908d4bd85967f0564[m
[32m+[m[32mstatic/js/main.f781ee89.js.LICENSE.txt,1685190608024,a966b5a07f0f1b04c22b1a4b17153cf651cb5386e5380302752c0fd378bf2f06[m
[32m+[m[32mstatic/js/787.c49e00e7.chunk.js.map,1685190608023,ab729b8a1e439b209352404a99fd0253de5e06f4db22b5c10141cd7c85c68781[m
[32m+[m[32mstatic/media/icon.35f11a99fb2a32658cd7.png,1685190608023,6d08c3862a35465d53b5ce8b5aa35cd93b4d4cfcc6e6b38d26103101cf20bcf5[m
[32m+[m[32mstatic/media/notFound-1.75c77d00f28c055f73df.png,1685190608023,c06c5e093df1df508c711d9b53f9513f135ee0889d01251fa716ad6d3e795a40[m
[32m+[m[32mstatic/media/question-1.9fb207f327cc85628ce9.png,1685190608023,7f3a94375dfa20661e6e9b1ce24d7305252c2ae1a42dc802f9683bce8cdddc1a[m
[32m+[m[32mstatic/media/question-2.436db4cdd9b084e8bf7f.png,1685190608023,17ee542fe34a1e6d1e4d99f7128372220702ae50253cbca14131ba03c95ee6cb[m
[32m+[m[32mstatic/js/main.f781ee89.js,1685190608024,4ffe582d545af6ff1496c4b23a91cb2f980c9818445012df783a370c32fb680e[m
[32m+[m[32mstatic/js/main.f781ee89.js.map,1685190608027,a84717389e86983e7c1650d26f453ecd7867f12ea8f66a617e79f389088f9bff[m
[1mdiff --git a/src/components/Pages/dds.jsx b/src/components/Pages/dds.jsx[m
[1mnew file mode 100644[m
[1mindex 0000000..aac584a[m
[1m--- /dev/null[m
[1m+++ b/src/components/Pages/dds.jsx[m
[36m@@ -0,0 +1,130 @@[m
[32m+[m[32mimport {[m[41m[m
[32m+[m[32m  Box,[m[41m[m
[32m+[m[32m  Button,[m[41m[m
[32m+[m[32m  HStack,[m[41m[m
[32m+[m[32m  Text,[m[41m[m
[32m+[m[32m  Textarea,[m[41m[m
[32m+[m[32m  VStack,[m[41m[m
[32m+[m[32m  useToast,[m[41m[m
[32m+[m[32m} from "@chakra-ui/react";[m[41m[m
[32m+[m[32mimport { SubmitHandler, useForm } from "react-hook-form";[m[41m[m
[32m+[m[32mimport emailjs from "emailjs-com";[m[41m[m
[32m+[m[32mimport React, { useState } from "react";[m[41m[m
[32m+[m[32mimport SubModalBox from "../Molecules/SubModalBox";[m[41m[m
[32m+[m[32mimport SubHeader from "../Templates/SubHeader";[m[41m[m
[32m+[m[41m[m
[32m+[m[32mfunction Feedback() {[m[41m[m
[32m+[m[32m  const {[m[41m[m
[32m+[m[32m    register,[m[41m[m
[32m+[m[32m    handleSubmit,[m[41m[m
[32m+[m[32m    formState: { errors },[m[41m[m
[32m+[m[32m  } = useForm();[m[41m[m
[32m+[m[32m  const [feedbackText, setFeedbackText] = useState < string > "";[m[41m[m
[32m+[m[32m  const toast = useToast();[m[41m[m
[32m+[m[41m[m
[32m+[m[32m  const submitMail = async (data) => {[m[41m[m
[32m+[m[32m    const serviceId = process.env.REACT_APP_EMAILJS_SERVICE_ID;[m[41m[m
[32m+[m[32m    const templateId = process.env.REACT_APP_EMAILJS_TEMPLATE_ID;[m[41m[m
[32m+[m[32m    const publicId = process.env.REACT_APP_EMAILJS_PUBLIC_ID;[m[41m[m
[32m+[m[32m    try {[m[41m[m
[32m+[m[32m      await emailjs.send([m[41m[m
[32m+[m[32m        serviceId,[m[41m[m
[32m+[m[32m        templateId,[m[41m[m
[32m+[m[32m        { feedback: data.feedback },[m[41m[m
[32m+[m[32m        publicId[m[41m[m
[32m+[m[32m 